### ISSUE TITLE
Unresolved reference: SentryEvent

### ISSUE THREAD

**Issue by sebj** [rickclephas/NSExceptionKt#1]
I'm trying to add NSExceptionKt to my project, which currently uses separate platform-native Sentry dependencies in the Android (Gradle) and iOS (Swift Package via Xcode) projects.

Following the instructions in the [README for Sentry support](https://github.com/rickclephas/NSExceptionKt/blob/master/nsexception-kt-sentry/README.md), adding the `dropSentryKotlinCrashEvent` and `setupSentry` functions as shown results in Kotlin compiler errors that `SentryEvent` cannot be resolved – presumably because Sentry is unknown to the shared/`iosMain` code.

I've instead done the following:
* Export NSExceptionKt as part of my shared framework in `build.gradle.kts` so that it can be used from iOS
  * `export("com.rickclephas.kmp:nsexception-kt-sentry:0.1.0")`
* Declared the NSExceptionKt dependency as `api(..)` rather than `implementation(..)`
* Called `SentryKt.dropKotlinCrashEvent` and `SentryKt.setSentryUnhandledExceptionHook` directly from my Swift iOS code

For my tests so far, this seems to work well – our crash reports are looking much improved in Sentry!

Do you see any potential issues with this method? If not, perhaps it could be worth documenting somewhere

**Comment by rickclephas** [comment]
Hi! Glad to hear your crash reports have improved!
The sample uses a similar setup with SPM. Making the shared module a [static](https://github.com/rickclephas/NSExceptionKt/blob/31d6dcafa5d082ccff1d87a8a7ecb4a30aca4041/sample/shared/build.gradle.kts#L18) framework solves the linker errors.

Interesting to see that exporting the dependency solves this as well. Will take a look at that 👍🏻 .

**Comment by sebj** [comment]
Ah, I suppose this might even be a non-issue based on our setup then. I hadn't checked the sample to be honest, but it seems we're using a similar Gradle setup with `isStatic = true` as well. We've had to use [a workaround](https://youtrack.jetbrains.com/issue/KT-53339/MPP-CocoaPods-The-static-framework-fails-to-install-on-a-real-iOS-device#focus=Comments-27-6360223.0-0) for an iOS build issue, which might have affected this though.

**Comment by rickclephas** [comment]
Thanks for the info. I hadn't run the sample on a real iOS device just yet. It also requires the mentioned workaround.
But reading your original comment again, I think I might have misunderstood the issue.
Did the compiler complain about an unresolved Kotlin reference to `SentryEvent` or did it complain about missing symbols during linking?

Using a static framework (with the workaround you mentioned) should solve any linking issues.
On the Kotlin side the following import should be enough to resolve the `SentryEvent` reference:
```kotlin
import Sentry.SentryEvent
```

**Comment by sebj** [comment]
> Did the compiler complain about an unresolved Kotlin reference to `SentryEvent` or did it complain about missing symbols during linking?

It complained about an unresolved Kotlin reference to SentryEvent

> On the Kotlin side the following import should be enough to resolve the `SentryEvent` reference:
> 
> ```kotlin
> import Sentry.SentryEvent
> ```

🤦‍♂️ D'oh, this worked perfectly, thanks! Android Studio didn't suggest any import at all

**Comment by rickclephas** [comment]
Cool! I have updated the code snippets to include the imports 👍🏻
