### ISSUE TITLE
Unhandled - missing symbol called > missing symbol called

### ISSUE THREAD

**Issue by simon-hogg** [rickclephas/NSExceptionKt#13]
Hi there, I am seeing a new crash in Sentry which looks allot like its coming from NSExceptionKt itself.
<img width="1171" alt="image" src="https://github.com/rickclephas/NSExceptionKt/assets/17775908/b206a48d-e917-423d-a313-cd867dc3b99d">

Am I reading this wrong? Thanks

Kotlin v1.8.20
Sentry-Cocoa v 8.3.3
NSExceptionKt v 0.1.5

**Comment by simon-hogg** [comment]
I just realised, 1.8.20 == 0.1.6 ... updating

**Comment by rickclephas** [comment]
Hi @simon-hogg, any update on this?

**Comment by simon-hogg** [comment]
> Hi @simon-hogg, any update on this?

Really sorry, this was not an issue with NSExceptionKt. I will close it.

I should have followed this up quicker. Thank you for all your great work in the KMM space, it's hugely valued.
