### ISSUE TITLE
nsexception-kt-core-cinterop-NSExceptionKtCoreObjC can't be exported with -Xexport-library

### ISSUE THREAD

**Issue by b95505017** [rickclephas/NSExceptionKt#25]
I follow [this guide](https://github.com/rickclephas/NSExceptionKt/blob/v1.0.0-BETA-1/NSExceptionKtCrashlytics/README.md) but failed.

> Interop library /Users/yuhsuanlin/.gradle/caches/modules-2/files-2.1/com.rickclephas.kmp/nsexception-kt-core-iossimulatorarm64/1.0.0-BETA-1/88e07bce40ac9786ccad5f354aef39e0fd1e6ae4/nsexception-kt-core-cinterop-NSExceptionKtCoreObjC can't be exported with -Xexport-library

> Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
>Undefined symbols:
>Linker command failed with exit code 1 (use -v to see invocation)

**Comment by rickclephas** [comment]
Hi thanks for opening an issue.

The warning regarding the interop library not being exported, is expected and shouldn't cause any issues.
Do you have some more details about the undefined symbols error?

It seems that the error about `CoreAudioTypes` can actually be quite misleading: https://forums.developer.apple.com/forums/thread/736152

**Comment by b95505017** [comment]
No idea. I tried to double clicked but no action item. Just compilation failed.

**Comment by b95505017** [comment]
Use Xcode 15.3 and got this
![截圖 2024-03-09 上午11 43 49](https://github.com/rickclephas/NSExceptionKt/assets/320815/9a108ad7-6bdd-41bd-99de-1721d8b43d90)

**Comment by rickclephas** [comment]
@b95505017 could you also share some details about the setup of your project?:
- how is the Firebase Crashlytics dependency added
- what version of the Firebase Crashlytics dependency are you using
