### ISSUE TITLE
No such module 'NSExceptionKtCrashlytics'

### ISSUE THREAD

**Issue by haydenkaizeta** [rickclephas/NSExceptionKt#28]
Error when compiling main swift class:

`iosApp.swift:5:8: No such module 'NSExceptionKtCrashlytics'`

`iosApp.swift`:

```
import UIKit
import SwiftUI
import ComposeApp
import FirebaseCore
import NSExceptionKtCrashlytics

@main
struct iosApp: App {
    init() {
        FirebaseApp.configure()
        NSExceptionKt.addReporter(.crashlytics(causedByStrategy: .append))
        MainKt.ContextInit()
        KoinKt.doInitKoin()
    }

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

`build.gradle.kts`:

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach {
            it.binaries.framework {
                isStatic = true
                export("com.rickclephas.kmp:nsexception-kt-core:1.0.0-BETA-1")
            }
    }

            val iosX64Main by getting
            val iosArm64Main by getting
            val iosSimulatorArm64Main by getting
            val iosMain by getting {
                dependencies {
                    // ios ktor engine impl
                    implementation(libs.ktor.client.darwin)

                    // crashlytics special exception handling
                    api(libs.nsexception) // com.rickclephas.kmp:nsexception-kt-core:1.0.0-BETA-1
                }
            }

**Comment by haydenkaizeta** [comment]
Ah on closer examination I realize I needed the SPM dep. Is there a cocoapods distribution?

**Comment by rickclephas** [comment]
> Ah on closer examination I realize I needed the SPM dep. Is there a cocoapods distribution?

No a CocoaPods distribution isn't provided
