### ISSUE TITLE
No such module 'NSExceptionKtCrashlytics'

### ISSUE THREAD

**Issue by deividasstr** [rickclephas/NSExceptionKt#31]
I am seeing a similar build issue to [this other issue](https://github.com/rickclephas/NSExceptionKt/issues/25). It is closed but the owner did not specify the solution.

Build error:
<img width="1001" alt="Screenshot 2024-07-26 at 11 17 32" src="https://github.com/user-attachments/assets/8d5f4f75-c1c8-4ac4-b3e1-8e314b0c07ed">
<img width="987" alt="Screenshot 2024-07-26 at 11 17 10" src="https://github.com/user-attachments/assets/4786efff-7f7f-4931-9974-1325c3617b7d">

Warning above:
<img width="999" alt="Screenshot 2024-07-26 at 12 01 11" src="https://github.com/user-attachments/assets/557ec02e-1ba0-4a5f-9332-f19ca669ffe3">

App delegate 
<img width="922" alt="Screenshot 2024-07-26 at 11 50 53" src="https://github.com/user-attachments/assets/98bcf7dc-64cf-412d-a1ea-4e9e2e600e4e">

Interesting that when I get linked to the `NSExceptionKt` class when clicking on it:
<img width="934" alt="Screenshot 2024-07-26 at 11 19 52" src="https://github.com/user-attachments/assets/30f05498-dce3-4e4c-a692-560bec7c28f9">

Crashlytics addition via SPM
<img width="847" alt="Screenshot 2024-07-26 at 11 18 35" src="https://github.com/user-attachments/assets/dd606eb2-3118-4d48-a967-b555427c6dac">
<img width="884" alt="Screenshot 2024-07-26 at 11 18 21" src="https://github.com/user-attachments/assets/fe8bfe38-bbbe-409f-ad8a-3b869a7bb001">

build.gradle setup uses a bit more modern approach, but should output the same:

```
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach {
        it.binaries.framework {
            baseName = "Shared"
            isStatic = true
            export(libs.ios.nsexception.tracker)
        }
    }
...
    sourceSets {
       iosMain {
            dependencies {
                implementation(libs.ktor.client.darwin)
                api(libs.ios.nsexception.tracker)
            }
        }

```

Tried using string dependency (`com.rickclephas.kmp:nsexception-kt-core:1.0.0-BETA-4`) instead of version catalogs, issue persists.

Bumping back to BETA1 did not work too.

Just FYI, when looking at a [sample](https://github.com/rickclephas/NSExceptionKt/blob/master/sample/shared/build.gradle.kts), I see that the dependency does not contain version.

**Comment by rickclephas** [comment]
It looks like the Swift part of the library wasn't added via SPM. `NSExceptionKtCrashlytics` is actually the Swift part for Crashlytics. The `NSExceptionKt` class is indeed coming from Kotlin.

Adding `https://github.com/rickclephas/NSExceptionKt` as a SPM dependency and then adding `NSExceptionKtCrashlytics` to your target should do the trick.

> Just FYI, when looking at a [sample](https://github.com/rickclephas/NSExceptionKt/blob/master/sample/shared/build.gradle.kts), I see that the dependency does not contain version.

Correct. The sample uses the [included build](https://github.com/rickclephas/NSExceptionKt/blob/33e5de6fe7d5dd2d1239b5a38ed5d34a29428900/sample/settings.gradle.kts#L13-L20) to build against the source instead of a released version.

**Comment by deividasstr** [comment]
Thanks alot for the swift reply! 

Yes, I missed this part of the docs:
`Now in your Xcode project [add](https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app) the NSExceptionKtCrashlytics dependency and update your Firebase configuration logic with a call to NSExceptionKt.addReporter:`

For a bit, I was confused what url exactly should I provide to the SPM, and it is the url of this github repo.

**Comment by jesjaa** [comment]
>Adding https://github.com/rickclephas/NSExceptionKt as a SPM dependency and then adding NSExceptionKtCrashlytics to your target should do the trick.


@rickclephas It would be helpful to clarify in the README that the NSExceptionKt package itself must be added via SPM. Currently it only mentions adding the NSExceptionKtCrashlytics dependency, which makes it sound something else.
