### ISSUE TITLE
Can't use firebase 11.0.0

### ISSUE THREAD

**Issue by b95505017** [rickclephas/NSExceptionKt#32]
[11.0.0 is released](https://firebase.google.com/support/release-notes/ios#11.0.0)
```
xcodebuild: error: Could not resolve package dependencies:
  Dependencies could not be resolved because 'nsexceptionkt' depends on 'firebase-ios-sdk' 9.3.0..<11.0.0 and root depends on 'firebase-ios-sdk' 11.0.0.
```

**Comment by rickclephas** [comment]
[v1.0.0-BETA-5](https://github.com/rickclephas/NSExceptionKt/releases/tag/v1.0.0-BETA-5) adds support for Firebase 11.x
